[project]
name = "tools"
version = "0.1.0"
dependencies = [
    "Pillow"
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
prompt = "prompt_tool.cli:main"
alarm = "alarm_tool.cli:main"
sprite = "sprite_tool.cli:main"
resize = "resize_tool.cli:main"
frame = "frame_tool.cli:main"
rename = "rename_tool.cli:main"
inject = "inject_tool.cli:main"
extract = "extract_tool.cli:main"
list = "list_tool.cli:main"

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]
ignore = []